version: '3.8'
services:

  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx
    volumes:
      - .:/var/www:rw
      - ./logs/nginx:/var/log/nginx/:rw
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      args:
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    container_name: php
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - .:/var/www

  postgres:
    build:
      context: ./docker/postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin:
